import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendVendorEmail({
  to,
  supplierName,
  skus,
  quantity,
  deadline,
  buyerName = "Procurement Officer",
  companyName = "SupplyPulse Client",
}: {
  to: string;
  supplierName: string;
  skus: string[];
  quantity: number;
  deadline: string;
  buyerName?: string;
  companyName?: string;
}): Promise<{ success: boolean; messageId?: string; error?: string }> {
  try {
    const { data, error } = await resend.emails.send({
      from: "SupplyPulse <onboarding@resend.dev>",
      to: [to],
      subject: `Urgent Supply Request — ${skus.join(", ")} — Needed by ${deadline}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #f9fafb; border-radius: 8px;">
          <div style="background: #0f172a; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
            <h1 style="color: #10b981; margin: 0; font-size: 24px;">SupplyPulse</h1>
            <p style="color: #94a3b8; margin: 4px 0 0;">Automated Procurement Communication</p>
          </div>

          <div style="background: white; padding: 24px; border-radius: 8px; border: 1px solid #e2e8f0;">
            <p style="color: #334155; font-size: 16px;">Dear <strong>${supplierName}</strong>,</p>

            <p style="color: #475569; line-height: 1.6;">
              We are reaching out regarding an urgent procurement need. Due to a disruption in our supply chain,
              we require your assistance to fulfil the following order on a priority basis.
            </p>

            <div style="background: #f8fafc; border-left: 4px solid #10b981; padding: 16px; margin: 20px 0; border-radius: 0 8px 8px 0;">
              <h3 style="color: #0f172a; margin: 0 0 12px;">Order Details</h3>
              <table style="width: 100%; border-collapse: collapse;">
                <tr>
                  <td style="padding: 8px 0; color: #64748b; font-size: 14px;">Products Required:</td>
                  <td style="padding: 8px 0; color: #0f172a; font-weight: bold;">${skus.join(", ")}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; color: #64748b; font-size: 14px;">Total Quantity:</td>
                  <td style="padding: 8px 0; color: #0f172a; font-weight: bold;">${quantity.toLocaleString()} units</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; color: #64748b; font-size: 14px;">Required By:</td>
                  <td style="padding: 8px 0; color: #ef4444; font-weight: bold;">${deadline}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; color: #64748b; font-size: 14px;">Buyer:</td>
                  <td style="padding: 8px 0; color: #0f172a;">${buyerName}, ${companyName}</td>
                </tr>
              </table>
            </div>

            <p style="color: #475569; line-height: 1.6;">
              Please confirm your availability and pricing at your earliest convenience.
              Time is critical for this order and we appreciate your prompt response.
            </p>

            <p style="color: #475569; line-height: 1.6;">
              This is an AI-assisted procurement request generated by SupplyPulse on behalf of ${companyName}.
            </p>

            <p style="color: #334155; margin-top: 24px;">
              Best regards,<br />
              <strong>${buyerName}</strong><br />
              ${companyName}<br />
              <span style="color: #10b981;">via SupplyPulse AI</span>
            </p>
          </div>

          <p style="color: #94a3b8; font-size: 12px; text-align: center; margin-top: 16px;">
            Sent via SupplyPulse — AI-Powered Supply Chain Crisis Management
          </p>
        </div>
      `,
    });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, messageId: data?.id };
  } catch (err) {
    return { success: false, error: String(err) };
  }
}
